
Original file line number	Diff line number	Diff line change
@@ -1,21 +1,50 @@
<div align="center">
<h1 align="center">
Auto-ShiXiBeiAn
</h1>
<p align="center">
ğŸ¥°å®ä¹ å¤‡æ¡ˆè‡ªåŠ¨æ‰“å¡è§£å†³æ–¹æ¡ˆğŸ¥°
</p>
<p align="center">
æ”¯æŒå¤šç”¨æˆ·ã€è‡ªå®šä¹‰ä½ç½®ä¸æ—¶é—´ã€å¾®ä¿¡æ¶ˆæ¯æ¨é€
</br>
</p>
</br>
<a target="_blank" href="https://b23.tv/hsaDxKf">è§†é¢‘æ•™ç¨‹</a>
</div>
</br>
